/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.edittrich.oauth2.proxy.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import de.edittrich.oauth2.proxy.model.ResponseError;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-07-24T15:14:00.334Z")

@Api(value = "authorize", description = "the authorize API")
public interface AuthorizeApi {

    @ApiOperation(value = "", notes = "Authorization of the client", response = Void.class, tags={ "Security", })
    @ApiResponses(value = { 
        @ApiResponse(code = 302, message = "Found (Moved Temporarily)", response = Void.class),
        @ApiResponse(code = 400, message = "Unexpected error", response = ResponseError.class) })
    
    @RequestMapping(value = "/authorize",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> authorizeGET( @NotNull@ApiParam(value = "Client ID", required = true) @RequestParam(value = "client_id", required = true) String clientId, @NotNull@ApiParam(value = "Response Type", required = true, allowableValues = "code", defaultValue = "code") @RequestParam(value = "response_type", required = true, defaultValue="code") String responseType, @NotNull@ApiParam(value = "Redirect URI", required = true) @RequestParam(value = "redirect_uri", required = true) String redirectUri,@ApiParam(value = "State") @RequestParam(value = "state", required = false) String state,@ApiParam(value = "Scopes list delimited with \"+\"") @RequestParam(value = "scope", required = false) String scope);

}
