/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.edittrich.oauth2.proxy.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import de.edittrich.oauth2.proxy.model.AccessToken;
import de.edittrich.oauth2.proxy.model.ResponseError;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-07-24T15:14:00.334Z")

@Api(value = "token", description = "the token API")
public interface TokenApi {

    @ApiOperation(value = "", notes = "Token", response = AccessToken.class, tags={ "Security", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = AccessToken.class),
        @ApiResponse(code = 400, message = "Unexpected error", response = ResponseError.class) })
    
    @RequestMapping(value = "/token",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<?> tokenPOST(@ApiParam(value = "Basic Authorization" ,required=true) @RequestHeader(value="Authorization", required=true) String authorization, @NotNull@ApiParam(value = "Redirect URI", required = true) @RequestParam(value = "redirect_uri", required = true) String redirectUri, @NotNull@ApiParam(value = "Type of Grant", required = true, allowableValues = "authorization_code, refresh_token", defaultValue = "authorization_code") @RequestParam(value = "grant_type", required = true, defaultValue="authorization_code") String grantType,@ApiParam(value = "Authorisation Code") @RequestParam(value = "code", required = false) String code,@ApiParam(value = "Refresh Token") @RequestParam(value = "refresh_token", required = false) String refreshToken);

}
