/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.edittrich.oauth2.data.api;

import de.edittrich.oauth2.data.model.CustomerData;
import de.edittrich.oauth2.data.model.ResponseError;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-07-28T14:45:09.156Z")

@Api(value = "customers", description = "the customers API")
public interface CustomersApi {

    @ApiOperation(value = "", notes = "Provides customer OAuth2 data for a given id", response = CustomerData.class, tags={ "Data", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CustomerData.class),
        @ApiResponse(code = 400, message = "Unexpected error", response = ResponseError.class) })
    
    @RequestMapping(value = "/customers/{customer_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<?> customerGET(@ApiParam(value = "CustomerId",required=true ) @PathVariable("customer_id") String customerId);


    @ApiOperation(value = "", notes = "Stores customer OAuth2 data for a given id", response = Void.class, tags={ "Data", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = Void.class),
        @ApiResponse(code = 400, message = "Unexpected error", response = ResponseError.class) })
    
    @RequestMapping(value = "/customers/{customer_id}",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> customerPOST(@ApiParam(value = "CustomerId",required=true ) @PathVariable("customer_id") String customerId,@ApiParam(value = "OAuth2 authorization state"  )  @Valid @RequestBody CustomerData customerData);

}
