server:
  context-path: /data
  port: 8444
  ssl:
    key-store: edittrich.jks
    key-store-password: mypassword    
    keyStoreType: JKS    

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

spring:
  jackson:
    date-format: de.edittrich.oauth2.data.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
logging:
  level:
    org.springframework.web: DEBUG
    de.edittrich: DEBUG